server:
  port: 8000

spring:
  application:
    name: @pom.artifactId@
  datasource:
    username: root
    password: r/hnbA5RjNdjnL0niIC1xtaGZ2+d8y3P8f4T5kH7ruKGce3KHVMOcfdNjkDEJGcOK/88ybJTl81Nh208I9dGtA==