server:
  port: 8000

spring:
  application:
    name: @pom.artifactId@
  datasource:
    username: root
    password: W6ZMm5WLI3wk1AfQ5JkplOkiRYEwCUu84+bxwBD4FxUdK14RvmRWqDjAtvqOHZAhtkrGb/Z/kg6sUs2iFMiXwg==